# Generated by Django 2.0.4 on 2018-06-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theorem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('definition', models.TextField(max_length=1000)),
                ('ggbFile64', models.TextField(max_length=10000000000)),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
